{
 "title": "Loki / Reads Resources",
 "tags": [ "loki" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(loki_build_info, cluster)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(loki_build_info{cluster=~\"$cluster\"}, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Query Frontend",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"query-frontend|loki\", pod=~\"loki-(query-frontend|read).*\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"query-frontend|loki\", pod=~\"loki-(query-frontend|read).*\", resource=\"cpu\"} > 0)",
     "legendFormat": "request"
    },
    {
     "expr": "min(container_spec_cpu_quota{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"query-frontend|loki\", pod=~\"loki-(query-frontend|read).*\"} / container_spec_cpu_period{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"query-frontend|loki\", pod=~\"loki-(query-frontend|read).*\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Memory (workingset)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(pod) (container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"query-frontend|loki\", pod=~\"loki-(query-frontend|read).*\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"query-frontend|loki\", pod=~\"loki-(query-frontend|read).*\", resource=\"memory\"} > 0)",
     "legendFormat": "request"
    },
    {
     "expr": "min(container_spec_memory_limit_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"query-frontend|loki\", pod=~\"loki-(query-frontend|read).*\"} > 0)",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Memory (go heap inuse)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (go_memstats_heap_inuse_bytes{cluster=~\"$cluster\", job=~\"($namespace)/loki-(query-frontend|read|single-binary)\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Query Scheduler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"query-scheduler|loki\", pod=~\"loki-(query-scheduler|read).*\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"query-scheduler|loki\", pod=~\"loki-(query-scheduler|read).*\", resource=\"cpu\"} > 0)",
     "legendFormat": "request"
    },
    {
     "expr": "min(container_spec_cpu_quota{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"query-scheduler|loki\", pod=~\"loki-(query-scheduler|read).*\"} / container_spec_cpu_period{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"query-scheduler|loki\", pod=~\"loki-(query-scheduler|read).*\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Memory (workingset)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(pod) (container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"query-scheduler|loki\",  pod=~\"loki-(query-scheduler|read).*\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"query-scheduler|loki\",  pod=~\"loki-(query-scheduler|read).*\", resource=\"memory\"} > 0)",
     "legendFormat": "request"
    },
    {
     "expr": "min(container_spec_memory_limit_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"query-scheduler|loki\",  pod=~\"loki-(query-scheduler|read).*\"} > 0)",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Memory (go heap inuse)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (go_memstats_heap_inuse_bytes{cluster=~\"$cluster\", job=~\"($namespace)/loki-(query-scheduler|read|single-binary)\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Querier",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"querier|loki\", pod=~\"loki-(querier|read).*\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"querier|loki\", pod=~\"loki-(querier|read).*\", resource=\"cpu\"} > 0)",
     "legendFormat": "request"
    },
    {
     "expr": "min(container_spec_cpu_quota{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"querier|loki\", pod=~\"loki-(querier|read).*\"} / container_spec_cpu_period{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"querier|loki\", pod=~\"loki-(querier|read).*\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Memory (workingset)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(pod) (container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"querier|loki\", pod=~\"loki-(querier|read).*\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"querier|loki\", pod=~\"loki-(querier|read).*\", resource=\"memory\"} > 0)",
     "legendFormat": "request"
    },
    {
     "expr": "min(container_spec_memory_limit_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"querier|loki\", pod=~\"loki-(querier|read).*\"} > 0)",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Memory (go heap inuse)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (go_memstats_heap_inuse_bytes{cluster=~\"$cluster\", job=~\"($namespace)/loki-(querier|read|single-binary)\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Index Gateway",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"loki|index-gateway\", pod=~\"(.*index-gateway.*|(loki|enterprise-logs)-read.*|loki-single-binary)\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"loki|index-gateway\", pod=~\"(.*index-gateway.*|(loki|enterprise-logs)-read.*|loki-single-binary)\", resource=\"cpu\"} > 0)",
     "legendFormat": "request"
    },
    {
     "expr": "min(container_spec_cpu_quota{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"loki|index-gateway\", pod=~\"(.*index-gateway.*|(loki|enterprise-logs)-read.*|loki-single-binary)\"} / container_spec_cpu_period{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"loki|index-gateway\", pod=~\"(.*index-gateway.*|(loki|enterprise-logs)-read.*|loki-single-binary)\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Memory (workingset)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(pod) (container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"loki|index-gateway\", pod=~\"(.*index-gateway.*|(loki|enterprise-logs)-read.*|loki-single-binary)\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"loki|index-gateway\", pod=~\"(.*index-gateway.*|(loki|enterprise-logs)-read.*|loki-single-binary)\", resource=\"memory\"} > 0)",
     "legendFormat": "request"
    },
    {
     "expr": "min(container_spec_memory_limit_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"loki|index-gateway\", pod=~\"(.*index-gateway.*|(loki|enterprise-logs)-read.*|loki-single-binary)\"} > 0)",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Memory (go heap inuse)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (go_memstats_heap_inuse_bytes{cluster=~\"$cluster\", job=~\"($namespace)/(.*index-gateway.*|(loki|enterprise-logs)-read.*|loki-single-binary)\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Disk Writes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_fs_writes_bytes_total{cluster=\"$cluster\",namespace=~\"$namespace\", container=~\"loki|index-gateway\", pod=~\"(.*index-gateway.*|(loki|enterprise-logs)-read.*|loki-single-binary)\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Reads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_fs_reads_bytes_total{cluster=\"$cluster\",namespace=~\"$namespace\", container=~\"loki|index-gateway\", pod=~\"(.*index-gateway.*|(loki|enterprise-logs)-read.*|loki-single-binary)\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Space Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\r\n  sum by(persistentvolumeclaim) (\r\n    kubelet_volume_stats_capacity_bytes{cluster=\"$cluster\", namespace=\"$namespace\", persistentvolumeclaim=~\".*loki-index-gateway.*\"}\r\n    -\r\n    kubelet_volume_stats_available_bytes{cluster=\"$cluster\", namespace=\"$namespace\", persistentvolumeclaim=~\".*loki-index-gateway.*\"}\r\n  )\r\n)\r\n/\r\nsum by(persistentvolumeclaim) (\r\n  kubelet_volume_stats_capacity_bytes{cluster=\"$cluster\", namespace=\"$namespace\", persistentvolumeclaim=~\".*loki-index-gateway.*\"}\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bloom Gateway",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-gateway|loki\", pod=~\"loki-(query-frontend|read).*\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-gateway|loki\", pod=~\"loki-(query-frontend|read).*\", resource=\"cpu\"} > 0)",
     "legendFormat": "request"
    },
    {
     "expr": "min(container_spec_cpu_quota{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-gateway|loki\", pod=~\"loki-(query-frontend|read).*\"} / container_spec_cpu_period{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-gateway|loki\", pod=~\"loki-(query-frontend|read).*\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Memory (workingset)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(pod) (container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-gateway|loki\", pod=~\"loki-(query-frontend|read).*\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-gateway|loki\", pod=~\"loki-(query-frontend|read).*\", resource=\"memory\"} > 0)",
     "legendFormat": "request"
    },
    {
     "expr": "min(container_spec_memory_limit_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-gateway|loki\", pod=~\"loki-(query-frontend|read).*\"} > 0)",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Memory (go heap inuse)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (go_memstats_heap_inuse_bytes{cluster=~\"$cluster\", job=~\"($namespace)/(.*bloom-gateway|loki-read|loki-single-binary)\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Disk Writes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(instance, pod, device) (rate(node_disk_written_bytes_total[$__rate_interval])) + ignoring(pod) group_right() (label_replace(count by(instance, pod, device) (container_fs_writes_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-gateway|loki\", pod=~\"loki-(query-frontend|read).*\", device!~\".*sda.*\"}), \"device\", \"$1\", \"device\", \"/dev/(.*)\") * 0)\n",
     "legendFormat": "{{pod}} - {{device}}"
    }
   ]
  },
  {
   "title": "Disk Reads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(instance, pod, device) (rate(node_disk_read_bytes_total[$__rate_interval])) + ignoring(pod) group_right() (label_replace(count by(instance, pod, device) (container_fs_writes_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-gateway|loki\", pod=~\"loki-(query-frontend|read).*\", device!~\".*sda.*\"}), \"device\", \"$1\", \"device\", \"/dev/(.*)\") * 0)\n",
     "legendFormat": "{{pod}} - {{device}}"
    }
   ]
  },
  {
   "title": "Disk Space Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by(persistentvolumeclaim) (kubelet_volume_stats_used_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\"} / kubelet_volume_stats_capacity_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\"}) and count by(persistentvolumeclaim) (kube_persistentvolumeclaim_labels{cluster=~\"$cluster\", namespace=~\"$namespace\",label_name=~\"bloom-gateway.*\"})",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Ingester",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"loki|ingester\", pod=~\"loki-(ingester|write).*\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"loki|ingester\", pod=~\"loki-(ingester|write).*\", resource=\"cpu\"} > 0)",
     "legendFormat": "request"
    },
    {
     "expr": "min(container_spec_cpu_quota{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"loki|ingester\", pod=~\"loki-(ingester|write).*\"} / container_spec_cpu_period{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"loki|ingester\", pod=~\"loki-(ingester|write).*\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Memory (workingset)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(pod) (container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"loki|ingester\", pod=~\"loki-(ingester|write).*\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"loki|ingester\", pod=~\"loki-(ingester|write).*\", resource=\"memory\"} > 0)",
     "legendFormat": "request"
    },
    {
     "expr": "min(container_spec_memory_limit_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"loki|ingester\", pod=~\"loki-(ingester|write).*\"} > 0)",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Memory (go heap inuse)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (go_memstats_heap_inuse_bytes{cluster=~\"$cluster\", job=~\"($namespace)/loki-(ingester|write|loki-single-binary)\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Ruler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rules",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod) (loki_prometheus_rule_group_rules{cluster=~\"$cluster\", job=~\"($namespace)/loki-ruler\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"ruler|loki\", pod=~\"loki-(ruler|backend).*\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"ruler|loki\", pod=~\"loki-(ruler|backend).*\", resource=\"cpu\"} > 0)",
     "legendFormat": "request"
    },
    {
     "expr": "min(container_spec_cpu_quota{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"ruler|loki\", pod=~\"loki-(ruler|backend).*\"} / container_spec_cpu_period{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"ruler|loki\", pod=~\"loki-(ruler|backend).*\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Memory (workingset)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(pod) (container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"ruler|loki\", pod=~\"loki-(ruler|backend).*\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"ruler|loki\", pod=~\"loki-(ruler|backend).*\", resource=\"memory\"} > 0)",
     "legendFormat": "request"
    },
    {
     "expr": "min(container_spec_memory_limit_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"ruler|loki\", pod=~\"loki-(ruler|backend).*\"} > 0)",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Memory (go heap inuse)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (go_memstats_heap_inuse_bytes{cluster=~\"$cluster\", job=~\"($namespace)/loki-(ruler|backend|single-binary)\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}