{
 "title": "Mimir / Compactor resources",
 "tags": [ "mimir" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(cortex_build_info, cluster)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(cortex_build_info{cluster=~\"$cluster\"}, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU and memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", namespace=~\"$namespace\",container=~\"compactor\", pod=~\"mimir.*\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(container_spec_cpu_quota{cluster=~\"$cluster\", namespace=~\"$namespace\",container=~\"compactor\", pod=~\"mimir.*\"} / container_spec_cpu_period{cluster=~\"$cluster\", namespace=~\"$namespace\",container=~\"compactor\", pod=~\"mimir.*\"})",
     "legendFormat": "limit"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$namespace\",container=~\"compactor\",resource=\"cpu\", pod=~\"mimir.*\"})",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Memory (go heap inuse)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (go_memstats_heap_inuse_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\",container=~\"compactor\", pod=~\"mimir.*\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory (RSS)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(pod) (container_memory_rss{cluster=~\"$cluster\", namespace=~\"$namespace\",container=~\"compactor\", pod=~\"mimir.*\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(container_spec_memory_limit_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\",container=~\"compactor\", pod=~\"mimir.*\"} > 0)",
     "legendFormat": "limit"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$namespace\",container=~\"compactor\",resource=\"memory\", pod=~\"mimir.*\"})",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Memory (workingset)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(pod) (container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\",container=~\"compactor\", pod=~\"mimir.*\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(container_spec_memory_limit_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\",container=~\"compactor\", pod=~\"mimir.*\"} > 0)",
     "legendFormat": "limit"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$namespace\",container=~\"compactor\",resource=\"memory\", pod=~\"mimir.*\"})",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Receive bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_network_receive_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"(.*mimir-)?compactor.*\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Transmit bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_network_transmit_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"(.*mimir-)?compactor.*\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk writes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_fs_writes_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"compactor\", pod=~\"mimir.*\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk reads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_fs_reads_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"compactor\", pod=~\"mimir.*\"}[$__rate_interval]))",
     "legendFormat": "{{pod}} "
    }
   ]
  },
  {
   "title": "Disk space utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by(persistentvolumeclaim) (\n  kubelet_volume_stats_used_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", persistentvolumeclaim=~\".*(compactor).*\"} /\n  kubelet_volume_stats_capacity_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", persistentvolumeclaim=~\".*(compactor).*\"}\n)\n",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  }
 ]
}